export const projects = [
  {
    name: "DevHub",
    githubUrl: "https://github.com/akashgupta1905/DevHub/tree/main/DevHub",
    image: "../../assets/devHub-project.png",
    projectUrl: "https://dev-hub-fawn.vercel.app/posts",
    deployed: true,
    category: ["react", "fs"],
  },
  {
    name: "Airbnb Clone",
    githubUrl: "https://github.com/akashgupta1905/Airbnb-Clone-Final",
    image: "../../assets/Airbnb-clone.png",
    projectUrl: "https://akashgupta1905.github.io/Airbnb-Clone-Final/",
    deployed: true,
    category: ["fs"],
  },
  {
    name: "Book Store",
    githubUrl: "https://github.com/akashgupta1905/Book_Store",
    image: "../../assets/book-store.png",
    projectUrl: "https://dreamy-nougat-dfbedb.netlify.app/",
    deployed: true,
    category: ["react", "fs"],
  },
  {
    name: "React Calculator",
    githubUrl: "https://github.com/akashgupta1905/React_Calc",
    image: "../../assets/react calculator.png",
    projectUrl: "https://react-calc-alpha.vercel.app/",
    deployed: true,
    category: ["fs"],
  },
  {
    name: "Youtube Clone",
    githubUrl: "https://github.com/akashgupta1905/Youtube-Clone",
    image: "../../assets/youtube-clone-project.png",
    projectUrl: "https://akashgupta1905.github.io/Youtube-Clone/",
    deployed: true,
    category: ["vanilla"],
  },
  {
    name: "Google Sheet Clone",
    githubUrl: "https://github.com/akashgupta1905/Google-sheet-clone",
    image: "../../assets/Google_sheet_clone.png",
    projectUrl: "https://akashgupta1905.github.io/Google-sheet-clone/",
    deployed: true,
    category: ["vanilla"],
  },
  {
    name: "Blinkit Clone",
    githubUrl: "https://github.com/akashgupta1905/Blinkit-Clone",
    image: "../../assets/Blinkit clone.png",
    projectUrl: "https://akashgupta1905.github.io/Blinkit-Clone/",
    deployed: true,
    category: ["vanilla"],
  },
  {
    name: "User IP-Address",
    githubUrl: "https://github.com/akashgupta1905/user-IP-address",
    image: "../../assets/IP-address.png",
    projectUrl: "https://akashgupta1905.github.io/user-IP-address/",
    deployed: true,
    category: ["vanilla"],
  },
  {
    name: "Portfolio Website",
    githubUrl: "",
    image: "../../assets/portfolio.png",
    category: ["fs"],
  },
  {
    name: "Crypto currency",
    githubUrl: "https://github.com/akashgupta1905/Cruptocurrency",
    image: "../../assets/Cryptocurrency.png",
    projectUrl: "https://akashgupta1905.github.io/Cruptocurrency/",
    deployed: true,
    category: ["vanilla"],
  },
  {
    name: "Cookpal",
    githubUrl: "https://github.com/akashgupta1905/F2-MODULE_TEST",
    image: "../../assets/Cookpal-clone.png",
    projectUrl: "https://akashgupta1905.github.io/F2-MODULE_TEST/",
    deployed: true,
    category: ["vanilla"],
  },
  
];
